language: node_js
node_js: "node"

before_install:
  - npm i -g pkg

script:
  - npm run build

after_success:
  - ls -lh build/binaries/
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh build/binaries/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/